/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_GWtQ3gUUl",
    "aws_user_pools_web_client_id": "3pbftgm1kvfqfaknbqmftnu3ml",
    "oauth": {}
};


export default awsmobile;
